services:

  ontology:

    image: kerxd/spring-boot-starter:latest
    container_name: starter-container

    ports:
      - "8080:8080"

    networks:
      - starter-network

    depends_on:
      - mysqldb

  mysqldb:

    image: mysql:latest
    container_name: mysql-container

    networks:
      - starter-network

    environment:
      - MYSQL_DATABASE=starter
      - MYSQL_ROOT_PASSWORD=root

    volumes:
      - mysql_db:/var/lib/mysql

  postgres_db:

    image: postgres:latest
    container_name: postgres-container

    networks:
      - starter-network

    environment:
      - POSTGRES_DB=starter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

#    volumes:
#      - mysql_db:/var/lib/mysql

volumes:
  mysql_db:

networks:
  starter-network: