#Production application properties

#Postgres Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/starter
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

#MySQL Database Config
#spring.datasource.url=jdbc:mysql://localhost:3306/starter
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver