#General application properties
spring.application.name=starter
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Indicate the active profile to be used: development or production
spring.profiles.active=development
