#General application properties
spring.application.name=starter
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#this is for showing the SQL queries formatted
spring.jpa.properties.hibernate.format_sql=true

#Indicate the active profile to be used: development, production or docker
spring.profiles.active=development
